# lets specify the api version that this deployment file will use
apiVersion: apps/v1
kind: Deployment
metadata:
  # Specify the name of the deployment
  name: platforms-depl
spec:
  replicas: 1
  #! Select the template we need
  selector:
    matchLabels:
      app: platformservice
  #! Define the POD and the CONTAINER we will use
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: fadygamil/platformservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: platforms-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platformservice
  ports:
    - name: platformservice
      protocol: TCP
      port: 80
      targetPort: 80
